#!/bin/bash

fileprefix="book.fi" 
echo "<meta charset=\"utf-8\">" >$fileprefix.html

cat plain-ui.fi.md readFile.fi.md simple-events.fi.md result-tables.fi.md gamestatus.fi.md linefeed.fi.md timing.fi.md timing-02.fi.md result-tables-02.fi.md result-tables-03.fi.md savedResults.fi.md settings.fi.md errorCanvas.fi.md statusbar.fi.md timingCanvas.fi.md helperCanvas.fi.md settingsDialog.fi.md fileError.fi.md aboutDialog.fi.md > book.fi.md


markdown $fileprefix.md >>$fileprefix.html
firefox $fileprefix.html  > /dev/null 2>&1 &
# rm $fileprefix.html

